import * as assert from 'node:assert';
import { readFile } from 'node:fs/promises';
import { test } from 'node:test';
import { extractPageMetaDataFromHtml } from './extractPageMetaDataFromHtml.mts';

test(extractPageMetaDataFromHtml.name, async () => {
  const html = await readFile(
    new URL(import.meta.url.replace(/\.test\.mts$/, '.html')),
    'utf8',
  );
  assert.deepStrictEqual(extractPageMetaDataFromHtml(html), {
    'title': [
      'Google 日本語入力物理フリックバージョン - YouTube',
      'Google 日本語入力物理フリックバージョン',
      'title in body',
    ],
    'datePublished': ['2016-03-31'],
    'description': [
      'Google 日本語入力チームからの新しいご提案です。',
      'Google 日本語入力チームからの新しいご提案です。',
    ],
    'duration': ['PT2M11S'],
    'genre': ['Science & Technology'],
    'height': ['720', '720'],
    'identifier': ['5LI1PysAlkU'],
    'interactionCount': ['123456'],
    'isFamilyFriendly': ['true'],
    'name': ['Google 日本語入力物理フリックバージョン'],
    'playerType': ['HTML5 Flash'],
    'regionsAllowed': ['JP'],
    'requiresSubscription': ['False'],
    'uploadDate': ['2016-03-31'],
    'width': ['1280', '1280'],
    'al:android:app_name': ['YouTube'],
    'al:android:package': ['com.google.android.youtube'],
    'al:ios:app_name': ['YouTube'],
    'al:ios:app_store_id': ['544007664'],
    'fb:app_id': ['87741124305'],
    'keywords': ['google, グーグル, 日本語入力, 日本語, IME, エイプリルフール'],
    'og:description': ['Google 日本語入力チームからの新しいご提案です。'],
    'og:image': ['https://i.ytimg.com/vi/5LI1PysAlkU/maxresdefault.jpg'],
    'og:image:height': ['720'],
    'og:image:width': ['1280'],
    'og:site_name': ['YouTube'],
    'og:title': ['Google 日本語入力物理フリックバージョン'],
    'og:type': ['video.other'],
    'og:url': ['https://www.youtube.com/watch?v=5LI1PysAlkU'],
    'og:video:height': ['720'],
    'og:video:secure_url': ['https://www.youtube.com/embed/5LI1PysAlkU'],
    'og:video:tag': [
      'google',
      'グーグル',
      '日本語入力',
      '日本語',
      'IME',
      'エイプリルフール',
      'ドラムセットバージョン',
      'モールスバージョン',
      'April Fool',
      'パタパタバージョン',
      'マジックハンドバージョン',
      'ピロピロバージョン',
      '物理フリック',
      '物理フリックバージョン',
      'フリック',
      'フリック入力',
    ],
    'og:video:type': ['text/html'],
    'og:video:url': ['https://www.youtube.com/embed/5LI1PysAlkU'],
    'og:video:width': ['1280'],
    'theme-color': ['rgba(255, 255, 255, 0.98)'],
    'twitter:app:id:googleplay': ['com.google.android.youtube'],
    'twitter:app:id:ipad': ['544007664'],
    'twitter:app:id:iphone': ['544007664'],
    'twitter:app:name:googleplay': ['YouTube'],
    'twitter:app:name:ipad': ['YouTube'],
    'twitter:app:name:iphone': ['YouTube'],
    'twitter:card': ['player'],
    'twitter:description': ['Google 日本語入力チームからの新しいご提案です。'],
    'twitter:image': ['https://i.ytimg.com/vi/5LI1PysAlkU/maxresdefault.jpg'],
    'twitter:player': ['https://www.youtube.com/embed/5LI1PysAlkU'],
    'twitter:player:height': ['720'],
    'twitter:player:width': ['1280'],
    'twitter:site': ['@youtube'],
    'twitter:title': ['Google 日本語入力物理フリックバージョン'],
    'twitter:url': ['https://www.youtube.com/watch?v=5LI1PysAlkU'],
  });
});
