// This file was generated by `npm run build:pageImages`
/* eslint-disable */
export interface PageImageData {
    path: string,
    width: number,
    height: number,
}
export const pageImages: Record<string, PageImageData | undefined> = {
    "/2018/monitor-stand": {
        "path": "/covers/M6w8jGfI/WmHuuZ8x/7--0uiKI.png",
        "width": 1200,
        "height": 630
    },
    "/2019/error-propagation": {
        "path": "/covers/SWD-1E4N/gOR8xg4X/VGuJD87d.png",
        "width": 1200,
        "height": 630
    },
    "/2019/gitlab-runner": {
        "path": "/covers/TmSvdGod/KslXvmhF/w2OtiiQV.png",
        "width": 1200,
        "height": 630
    },
    "/2020/new-computer": {
        "path": "/covers/-AL1gWae/5NcKEzYS/3g8Yv8UV.png",
        "width": 1200,
        "height": 630
    },
    "/2021/au-denki": {
        "path": "/covers/9cPn0k2Z/mLkprLaS/52Jb3wPD.png",
        "width": 1200,
        "height": 630
    },
    "/2021/aws-errors": {
        "path": "/covers/TzRZIKCA/IwwZmTor/Fg6vY7Bo.png",
        "width": 1200,
        "height": 630
    },
    "/2021/ipad-case": {
        "path": "/covers/3pChiagg/5SSDoUaa/FExFcUFh.png",
        "width": 1200,
        "height": 630
    },
    "/2021/nextjs": {
        "path": "/covers/s373Le5-/hjgV9EEr/5yXBEKLr.png",
        "width": 1200,
        "height": 630
    },
    "/2021/nextjs-https": {
        "path": "/covers/ZX-cXk49/-s_WZi4X/QkzOoqbY.png",
        "width": 1200,
        "height": 630
    },
    "/2021/nextjs12": {
        "path": "/covers/FqWvXwk8/dpk1NjN1/edrSL-IG.png",
        "width": 1200,
        "height": 630
    },
    "/2022/image-preprocessor": {
        "path": "/covers/foR4ezoK/TcrXu_Hv/u98qyJzm.png",
        "width": 1200,
        "height": 630
    },
    "/2022/iphone12": {
        "path": "/covers/C4al8FNS/CzuuVKJ8/erX0O0jD.png",
        "width": 1200,
        "height": 630
    },
    "/2022/page-images": {
        "path": "/covers/yEbsLghZ/WQA_EioO/A-IwJvYb.png",
        "width": 1200,
        "height": 630
    },
    "/app/device": {
        "path": "/covers/6bAdtvDW/lrztfOaG/daI7HFDu.png",
        "width": 1200,
        "height": 630
    },
    "/author": {
        "path": "/covers/2NbUOuVG/FiPxOqdo/bHqmDCOr.png",
        "width": 1200,
        "height": 630
    },
    "": {
        "path": "/covers/47DEQpj8/7BmRsuWM/WDZhB1Wt.png",
        "width": 1200,
        "height": 630
    },
    "/markdown": {
        "path": "/covers/tiihd--T/0i7-Oh96/JEPZt-bO.png",
        "width": 1200,
        "height": 630
    }
};
