// This file was generated by @gjbkz/gojabako.zone-build-pagelist
/* eslint-disable */
export interface PageData {
    pathname: string,
    title: string,
    filePath: string,
    publishedAt: string,
    updatedAt: string,
    commitCount: number,
    archiveOf?: string,
    description?: string,
}
export const pageListByPublishedAt: Array<PageData> = [
    {
        "pathname": "/2022/dpop",
        "title": "DPoPのブラウザ実装",
        "filePath": "pages/2022/dpop/index.page.md",
        "publishedAt": "2022-08-29T02:37:13+09:00",
        "updatedAt": "2022-09-03T09:56:55+09:00",
        "commitCount": 8
    },
    {
        "pathname": "/2022/disabled-form-element",
        "title": "disabledなフォーム要素はsubmitされない",
        "filePath": "pages/2022/disabled-form-element/index.page.md",
        "publishedAt": "2022-08-28T18:13:17+09:00",
        "updatedAt": "2022-09-01T01:03:29+09:00",
        "commitCount": 6
    },
    {
        "pathname": "/2022/ag06modification",
        "title": "AG06にマイクをGoProマウントする",
        "filePath": "pages/2022/ag06modification/index.page.md",
        "publishedAt": "2022-04-09T13:59:15+09:00",
        "updatedAt": "2022-04-09T13:59:15+09:00",
        "commitCount": 1
    },
    {
        "pathname": "/app/device",
        "title": "デバイス情報の確認",
        "filePath": "pages/app/device/index.page.md",
        "publishedAt": "2022-02-26T00:47:20+09:00",
        "updatedAt": "2022-08-29T23:27:52+09:00",
        "commitCount": 4
    },
    {
        "pathname": "/2022/iphone12",
        "title": "Appleでオンライン購入したiPhone 12がau回線で使えるようになるまで",
        "filePath": "pages/2022/iphone12/index.page.md",
        "publishedAt": "2022-02-13T18:21:58+09:00",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 2
    },
    {
        "pathname": "/2022/page-images",
        "title": "ブログ記事の画像を生成する",
        "filePath": "pages/2022/page-images/index.page.md",
        "publishedAt": "2022-02-11T23:48:29+09:00",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 4
    },
    {
        "pathname": "/2022/image-preprocessor",
        "title": "next/imageが遅いのでやめた",
        "filePath": "pages/2022/image-preprocessor/index.page.md",
        "publishedAt": "2022-02-05T18:20:17+09:00",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 3
    },
    {
        "pathname": "/2021/aws-errors",
        "title": "AWSの開発でたまに遭うエラーと原因",
        "filePath": "pages/2021/aws-errors/index.page.md",
        "publishedAt": "2021-12-17T00:15:30+09:00",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 4
    },
    {
        "pathname": "/2021/ipad-case",
        "title": "iPad Proケースの製作",
        "filePath": "pages/2021/ipad-case/index.page.md",
        "publishedAt": "2021-12-13T22:53:16+09:00",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 3
    },
    {
        "pathname": "/2021/au-denki",
        "title": "auでんきの使用量をCSVにする",
        "filePath": "pages/2021/au-denki/index.page.md",
        "publishedAt": "2021-12-01T00:59:21+09:00",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 5
    },
    {
        "pathname": "/2021/nextjs12",
        "title": "Next.js 12にしました",
        "filePath": "pages/2021/nextjs12/index.page.md",
        "publishedAt": "2021-10-29T22:24:14+09:00",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 5
    },
    {
        "pathname": "/author",
        "title": "伊藤 慶 - Kei Ito",
        "filePath": "pages/author.page.md",
        "publishedAt": "2021-10-13T20:35:53+09:00",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 5
    },
    {
        "pathname": "/2021/nextjs-https",
        "title": "Next.jsの開発環境をHTTPSにする",
        "filePath": "pages/2021/nextjs-https/index.page.md",
        "publishedAt": "2021-10-11T00:26:45+09:00",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 6
    },
    {
        "pathname": "/2021/nextjs",
        "title": "サイトをNext.js + Vercelに移行した",
        "filePath": "pages/2021/nextjs/index.page.md",
        "publishedAt": "2021-10-05T23:51:46+09:00",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 13
    },
    {
        "pathname": "/markdown",
        "title": "Markdown動作確認およびタイトルが長い場合の画像生成等の検証用記事",
        "filePath": "pages/markdown.page.md",
        "publishedAt": "2021-09-30T00:39:26+09:00",
        "updatedAt": "2022-08-29T23:27:52+09:00",
        "commitCount": 22
    },
    {
        "pathname": "",
        "title": "Gojabako Zone",
        "filePath": "pages/index.tsx",
        "publishedAt": "2021-09-29T00:33:31+09:00",
        "updatedAt": "2022-09-03T17:58:06+09:00",
        "commitCount": 25
    },
    {
        "pathname": "/2020/new-computer",
        "title": "ラックマウントPC",
        "filePath": "pages/2020/new-computer/index.page.md",
        "publishedAt": "2020-06-08T14:23:25Z",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 3,
        "archiveOf": "https://kei-itof.goat.me/s3xAnADIzK"
    },
    {
        "pathname": "/2019/gitlab-runner",
        "title": "GitLab Runner環境をCloudFormationでつくる",
        "filePath": "pages/2019/gitlab-runner/index.page.md",
        "publishedAt": "2019-05-12T16:30:37Z",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 2,
        "archiveOf": "https://kei-itof.goat.me/hFPAYi8W52"
    },
    {
        "pathname": "/2019/error-propagation",
        "title": "加重平均の誤差伝播",
        "filePath": "pages/2019/error-propagation/index.page.md",
        "publishedAt": "2019-04-26T18:46:08Z",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 3,
        "archiveOf": "https://kei-itof.goat.me/heZeNIQCCQ"
    },
    {
        "pathname": "/2018/monitor-stand",
        "title": "モニタースタンドに棚をつけるDIY記録",
        "filePath": "pages/2018/monitor-stand/index.page.md",
        "publishedAt": "2018-11-29T17:01:41Z",
        "updatedAt": "2022-03-03T23:51:55+09:00",
        "commitCount": 5,
        "archiveOf": "https://kei-itof.goat.me/di7WvuuNG0"
    }
];
export const pageListByUpdatedAt: Array<PageData> = [15,0,1,14,3,2,11,5,4,6,10,12,13,8,7,9,16,17,18,19]
.map((index) => pageListByPublishedAt[index]);