// This file was generated by `npm run build:pageList`
/* eslint-disable */
export interface PageData {
    pathname: string,
    title: string,
    filePath: string,
    publishedAt: string,
    updatedAt: string,
    commitCount: number,
    archiveOf?: string,
    description?: string,
}
export const pageListByPublishedAt: Array<PageData> = [
    {
        "pathname": "/markdown",
        "title": "Markdown動作確認およびタイトルが長い場合の画像生成等の検証用記事",
        "filePath": "pages/markdown.page.md",
        "publishedAt": "2022-03-03T14:48:20.126Z",
        "updatedAt": "2022-03-03T14:48:20.126Z",
        "commitCount": 0
    },
    {
        "pathname": "",
        "title": "Gojabako Zone",
        "filePath": "pages/index.tsx",
        "publishedAt": "2022-03-03T14:48:20.109Z",
        "updatedAt": "2022-03-03T14:48:20.109Z",
        "commitCount": 0
    },
    {
        "pathname": "/author",
        "title": "伊藤 慶 - Kei Ito",
        "filePath": "pages/author.page.md",
        "publishedAt": "2022-03-03T14:48:20.093Z",
        "updatedAt": "2022-03-03T14:48:20.093Z",
        "commitCount": 0
    },
    {
        "pathname": "/app/device",
        "title": "デバイス情報の確認",
        "filePath": "pages/app/device/index.page.md",
        "publishedAt": "2022-03-03T14:48:20.077Z",
        "updatedAt": "2022-03-03T14:48:20.077Z",
        "commitCount": 0
    },
    {
        "pathname": "/2022/page-images",
        "title": "ブログ記事の画像を生成する",
        "filePath": "pages/2022/page-images/index.page.md",
        "publishedAt": "2022-03-03T14:48:20.060Z",
        "updatedAt": "2022-03-03T14:48:20.060Z",
        "commitCount": 0
    },
    {
        "pathname": "/2022/iphone12",
        "title": "Appleでオンライン購入したiPhone 12がau回線で使えるようになるまで",
        "filePath": "pages/2022/iphone12/index.page.md",
        "publishedAt": "2022-03-03T14:48:20.044Z",
        "updatedAt": "2022-03-03T14:48:20.044Z",
        "commitCount": 0
    },
    {
        "pathname": "/2022/image-preprocessor",
        "title": "next/imageが遅いのでやめた",
        "filePath": "pages/2022/image-preprocessor/index.page.md",
        "publishedAt": "2022-03-03T14:48:20.027Z",
        "updatedAt": "2022-03-03T14:48:20.027Z",
        "commitCount": 0
    },
    {
        "pathname": "/2021/nextjs12",
        "title": "Next.js 12にしました",
        "filePath": "pages/2021/nextjs12/index.page.md",
        "publishedAt": "2022-03-03T14:48:20.011Z",
        "updatedAt": "2022-03-03T14:48:20.011Z",
        "commitCount": 0
    },
    {
        "pathname": "/2021/nextjs-https",
        "title": "Next.jsの開発環境をHTTPSにする",
        "filePath": "pages/2021/nextjs-https/index.page.md",
        "publishedAt": "2022-03-03T14:48:19.994Z",
        "updatedAt": "2022-03-03T14:48:19.994Z",
        "commitCount": 0
    },
    {
        "pathname": "/2021/nextjs",
        "title": "サイトをNext.js + Vercelに移行した",
        "filePath": "pages/2021/nextjs/index.page.md",
        "publishedAt": "2022-03-03T14:48:19.976Z",
        "updatedAt": "2022-03-03T14:48:19.976Z",
        "commitCount": 0
    },
    {
        "pathname": "/2021/ipad-case",
        "title": "iPad Proケースの製作",
        "filePath": "pages/2021/ipad-case/index.page.md",
        "publishedAt": "2022-03-03T14:48:19.959Z",
        "updatedAt": "2022-03-03T14:48:19.959Z",
        "commitCount": 0
    },
    {
        "pathname": "/2021/aws-errors",
        "title": "AWSの開発でたまに遭うエラーと原因",
        "filePath": "pages/2021/aws-errors/index.page.md",
        "publishedAt": "2022-03-03T14:48:19.941Z",
        "updatedAt": "2022-03-03T14:48:19.941Z",
        "commitCount": 0
    },
    {
        "pathname": "/2021/au-denki",
        "title": "auでんきの使用量をCSVにする",
        "filePath": "pages/2021/au-denki/index.page.md",
        "publishedAt": "2022-03-03T14:48:19.924Z",
        "updatedAt": "2022-03-03T14:48:19.924Z",
        "commitCount": 0
    },
    {
        "pathname": "/2020/new-computer",
        "title": "ラックマウントPC",
        "filePath": "pages/2020/new-computer/index.page.md",
        "publishedAt": "2020-06-08T14:23:25Z",
        "updatedAt": "2022-03-03T14:48:19.907Z",
        "commitCount": 0,
        "archiveOf": "https://kei-itof.goat.me/s3xAnADIzK"
    },
    {
        "pathname": "/2019/gitlab-runner",
        "title": "GitLab Runner環境をCloudFormationでつくる",
        "filePath": "pages/2019/gitlab-runner/index.page.md",
        "publishedAt": "2019-05-12T16:30:37Z",
        "updatedAt": "2022-03-03T14:48:19.889Z",
        "commitCount": 0,
        "archiveOf": "https://kei-itof.goat.me/hFPAYi8W52"
    },
    {
        "pathname": "/2019/error-propagation",
        "title": "加重平均の誤差伝播",
        "filePath": "pages/2019/error-propagation/index.page.md",
        "publishedAt": "2019-04-26T18:46:08Z",
        "updatedAt": "2022-03-03T14:48:19.872Z",
        "commitCount": 0,
        "archiveOf": "https://kei-itof.goat.me/heZeNIQCCQ"
    },
    {
        "pathname": "/2018/monitor-stand",
        "title": "モニタースタンドに棚をつけるDIY記録",
        "filePath": "pages/2018/monitor-stand/index.page.md",
        "publishedAt": "2018-11-29T17:01:41Z",
        "updatedAt": "2022-03-03T14:48:19.854Z",
        "commitCount": 0,
        "archiveOf": "https://kei-itof.goat.me/di7WvuuNG0"
    }
];
export const pageListByUpdatedAt: Array<PageData> = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16].map((index) => pageListByPublishedAt[index]);
