// This file was generated by `npm run build:pageImages`
/* eslint-disable */
export interface PageImageData {
    path: string,
    width: number,
    height: number,
}
export const pageImages: Record<string, PageImageData | undefined> = {
    "/2018/monitor-stand": {
        "path": "/covers/M6w8jGfI/C2-Y8cjd.png",
        "width": 1200,
        "height": 630
    },
    "/2019/error-propagation": {
        "path": "/covers/SWD-1E4N/ZlUDNA7P.png",
        "width": 1200,
        "height": 630
    },
    "/2019/gitlab-runner": {
        "path": "/covers/TmSvdGod/4dQrixIl.png",
        "width": 1200,
        "height": 630
    },
    "/2020/new-computer": {
        "path": "/covers/-AL1gWae/trCiKMhT.png",
        "width": 1200,
        "height": 630
    },
    "/2021/au-denki": {
        "path": "/covers/9cPn0k2Z/eF0jBzyy.png",
        "width": 1200,
        "height": 630
    },
    "/2021/aws-errors": {
        "path": "/covers/TzRZIKCA/itd5oMYi.png",
        "width": 1200,
        "height": 630
    },
    "/2021/ipad-case": {
        "path": "/covers/3pChiagg/SAnCUVLF.png",
        "width": 1200,
        "height": 630
    },
    "/2021/nextjs": {
        "path": "/covers/s373Le5-/vWHER8Dk.png",
        "width": 1200,
        "height": 630
    },
    "/2021/nextjs-https": {
        "path": "/covers/ZX-cXk49/agnbSFFQ.png",
        "width": 1200,
        "height": 630
    },
    "/2021/nextjs12": {
        "path": "/covers/FqWvXwk8/CF44ti-s.png",
        "width": 1200,
        "height": 630
    },
    "/2022/image-preprocessor": {
        "path": "/covers/foR4ezoK/dZLfIiR5.png",
        "width": 1200,
        "height": 630
    },
    "/2022/iphone12": {
        "path": "/covers/C4al8FNS/aWTDW8Id.png",
        "width": 1200,
        "height": 630
    },
    "/2022/page-images": {
        "path": "/covers/yEbsLghZ/gQv04uqG.png",
        "width": 1200,
        "height": 630
    },
    "/app/device": {
        "path": "/covers/6bAdtvDW/R9FgXYDj.png",
        "width": 1200,
        "height": 630
    },
    "/author": {
        "path": "/covers/2NbUOuVG/j3Zz3iXi.png",
        "width": 1200,
        "height": 630
    },
    "": {
        "path": "/covers/47DEQpj8/duEz2g_1.png",
        "width": 1200,
        "height": 630
    },
    "/markdown": {
        "path": "/covers/tiihd--T/wkoJINX2.png",
        "width": 1200,
        "height": 630
    }
};
