// This file was generated by `npm run build:pageList`
/* eslint-disable */
export interface PageData {
    pathname: string,
    title: string,
    filePath: string,
    publishedAt: string,
    updatedAt: string,
    commitCount: number,
    archiveOf?: string,
}
export const pageListByPublishedAt: Array<PageData> = [
    {
        "pathname": "/2022/iphone12",
        "title": "Appleでオンライン購入したiPhone 12がau回線で使えるようになるまで",
        "filePath": "src/pages/2022/iphone12/index.page.md",
        "publishedAt": "2022-02-13T18:21:58+09:00",
        "updatedAt": "2022-02-13T18:21:58+09:00",
        "commitCount": 1
    },
    {
        "pathname": "/2022/page-images",
        "title": "ブログ記事の画像を生成できるようにした",
        "filePath": "src/pages/2022/page-images/index.page.md",
        "publishedAt": "2022-02-11T23:48:29+09:00",
        "updatedAt": "2022-02-12T16:20:17+09:00",
        "commitCount": 2
    },
    {
        "pathname": "/2022/image-preprocessor",
        "title": "next/imageが遅いのでやめた",
        "filePath": "src/pages/2022/image-preprocessor/index.page.md",
        "publishedAt": "2022-02-05T18:20:17+09:00",
        "updatedAt": "2022-02-11T21:28:55+09:00",
        "commitCount": 2
    },
    {
        "pathname": "/2021/aws-errors",
        "title": "AWSの開発で見たエラーと原因",
        "filePath": "src/pages/2021/aws-errors/index.page.md",
        "publishedAt": "2021-12-17T00:15:30+09:00",
        "updatedAt": "2021-12-23T09:42:07+09:00",
        "commitCount": 2
    },
    {
        "pathname": "/2021/ipad-case",
        "title": "iPad Proケースの製作",
        "filePath": "src/pages/2021/ipad-case/index.page.md",
        "publishedAt": "2021-12-13T22:53:16+09:00",
        "updatedAt": "2021-12-14T01:16:34+09:00",
        "commitCount": 2
    },
    {
        "pathname": "/2021/au-denki",
        "title": "auでんきの使用量をCSVにする",
        "filePath": "src/pages/2021/au-denki/index.page.md",
        "publishedAt": "2021-12-01T00:59:21+09:00",
        "updatedAt": "2021-12-01T01:30:59+09:00",
        "commitCount": 4
    },
    {
        "pathname": "/2021/nextjs12",
        "title": "Next.js 12にしました",
        "filePath": "src/pages/2021/nextjs12/index.page.md",
        "publishedAt": "2021-10-29T22:24:14+09:00",
        "updatedAt": "2021-11-25T12:56:34+09:00",
        "commitCount": 4
    },
    {
        "pathname": "/author",
        "title": "伊藤 慶 - Kei Ito",
        "filePath": "src/pages/author.page.md",
        "publishedAt": "2021-10-13T20:35:53+09:00",
        "updatedAt": "2022-02-16T23:55:35+09:00",
        "commitCount": 4
    },
    {
        "pathname": "/2021/nextjs-https",
        "title": "Next.jsの開発環境をHTTPSにしました",
        "filePath": "src/pages/2021/nextjs-https/index.page.md",
        "publishedAt": "2021-10-11T00:26:45+09:00",
        "updatedAt": "2021-11-25T12:56:34+09:00",
        "commitCount": 4
    },
    {
        "pathname": "/2021/nextjs",
        "title": "サイトをNext.js + Vercelに移行しました",
        "filePath": "src/pages/2021/nextjs/index.page.md",
        "publishedAt": "2021-10-05T23:51:46+09:00",
        "updatedAt": "2022-02-16T23:55:35+09:00",
        "commitCount": 11
    },
    {
        "pathname": "/markdown",
        "title": "Markdown動作確認およびタイトルが長い場合の画像生成等の検証用記事",
        "filePath": "src/pages/markdown.page.md",
        "publishedAt": "2021-09-30T00:39:26+09:00",
        "updatedAt": "2022-02-12T16:08:39+09:00",
        "commitCount": 18
    },
    {
        "pathname": "",
        "title": "Gojabako Zone",
        "filePath": "src/pages/index.tsx",
        "publishedAt": "2021-09-29T00:33:31+09:00",
        "updatedAt": "2022-02-16T23:55:35+09:00",
        "commitCount": 19
    },
    {
        "pathname": "/2020/new-computer",
        "title": "ラックマウントPC",
        "filePath": "src/pages/2020/new-computer/index.page.md",
        "publishedAt": "2020-06-08T14:23:25Z",
        "updatedAt": "2022-02-16T12:01:24+09:00",
        "commitCount": 2,
        "archiveOf": "https://kei-itof.goat.me/s3xAnADIzK"
    },
    {
        "pathname": "/2019/gitlab-runner",
        "title": "GitLab Runner環境をCloudFormationでつくる",
        "filePath": "src/pages/2019/gitlab-runner/index.page.md",
        "publishedAt": "2019-05-12T16:30:37Z",
        "updatedAt": "2022-02-16T01:01:22+09:00",
        "commitCount": 1,
        "archiveOf": "https://kei-itof.goat.me/hFPAYi8W52"
    },
    {
        "pathname": "/2018/monitor-stand",
        "title": "モニタースタンドに棚をつけるDIY記録",
        "filePath": "src/pages/2018/monitor-stand/index.page.md",
        "publishedAt": "2018-11-29T17:01:41Z",
        "updatedAt": "2022-02-19T21:45:37+09:00",
        "commitCount": 3,
        "archiveOf": "https://kei-itof.goat.me/di7WvuuNG0"
    }
];
export const pageListByUpdatedAt: Array<PageData> = [14,11,7,9,12,13,0,1,10,2,3,4,5,6,8].map((index) => pageListByPublishedAt[index]);
