// This file was generated by `npm run build:pageImages`
/* eslint-disable */
export interface PageImageData {
    path: string,
    width: number,
    height: number,
}
export const pageImages: Record<string, PageImageData | undefined> = {
    "/2018/monitor-stand": {
        "path": "/covers/M6w8jGfI/kBsaiFv3.png",
        "width": 1200,
        "height": 630
    },
    "/2019/gitlab-runner": {
        "path": "/covers/TmSvdGod/jJ_T9p5L.png",
        "width": 1200,
        "height": 630
    },
    "/2020/new-computer": {
        "path": "/covers/-AL1gWae/4vTpq3sy.png",
        "width": 1200,
        "height": 630
    },
    "/2021/au-denki": {
        "path": "/covers/9cPn0k2Z/bBx1gzB3.png",
        "width": 1200,
        "height": 630
    },
    "/2021/aws-errors": {
        "path": "/covers/TzRZIKCA/RIzPTX2u.png",
        "width": 1200,
        "height": 630
    },
    "/2021/ipad-case": {
        "path": "/covers/3pChiagg/9781MoAm.png",
        "width": 1200,
        "height": 630
    },
    "/2021/nextjs": {
        "path": "/covers/s373Le5-/iR0axFxV.png",
        "width": 1200,
        "height": 630
    },
    "/2021/nextjs-https": {
        "path": "/covers/ZX-cXk49/HsdBFVJn.png",
        "width": 1200,
        "height": 630
    },
    "/2021/nextjs12": {
        "path": "/covers/FqWvXwk8/UrbE5M52.png",
        "width": 1200,
        "height": 630
    },
    "/2022/image-preprocessor": {
        "path": "/covers/foR4ezoK/YRgxOX6r.png",
        "width": 1200,
        "height": 630
    },
    "/2022/iphone12": {
        "path": "/covers/C4al8FNS/2pNsw7kt.png",
        "width": 1200,
        "height": 630
    },
    "/2022/page-images": {
        "path": "/covers/yEbsLghZ/mw2_qK9v.png",
        "width": 1200,
        "height": 630
    },
    "/author": {
        "path": "/covers/2NbUOuVG/lwyJ1xkX.png",
        "width": 1200,
        "height": 630
    },
    "": {
        "path": "/covers/47DEQpj8/MrIyyBSJ.png",
        "width": 1200,
        "height": 630
    },
    "/markdown": {
        "path": "/covers/tiihd--T/bdB5jLJH.png",
        "width": 1200,
        "height": 630
    }
};
