// This file was generated by `npm run build:pageList`
/* eslint-disable */
import {JSON} from '../packages/es/global';
export interface PageData {
    pathname: string,
    title: string,
    filePath: string,
    publishedAt: string,
    updatedAt: string,
    commitCount: number,
    cover: {
        path: string,
        width: number,
        height: number,
    },
}
export const pageListByPublishedAt: Array<PageData> = JSON.parse(`[
{"pathname":"/2022/image-preprocessor","title":"next/imageが遅いのでやめた","filePath":"src/pages/2022/image-preprocessor/index.page.md","publishedAt":"2022-02-05T18:20:17+09:00","updatedAt":"2022-02-05T18:20:17+09:00","commitCount":1,"cover":{"path":"post-images/v1/foR4ezoK.png","width":1200,"height":630}},
{"pathname":"/2021/aws-errors","title":"AWSの開発で見たエラーと原因","filePath":"src/pages/2021/aws-errors/index.page.md","publishedAt":"2021-12-17T00:15:30+09:00","updatedAt":"2021-12-23T09:42:07+09:00","commitCount":2,"cover":{"path":"post-images/v1/TzRZIKCA.png","width":1200,"height":630}},
{"pathname":"/2021/ipad-case","title":"iPad Proケースの製作","filePath":"src/pages/2021/ipad-case/index.page.md","publishedAt":"2021-12-13T22:53:16+09:00","updatedAt":"2021-12-14T01:16:34+09:00","commitCount":2,"cover":{"path":"post-images/v1/3pChiagg.png","width":1200,"height":630}},
{"pathname":"/2021/au-denki","title":"auでんきの使用量をCSVにする","filePath":"src/pages/2021/au-denki/index.page.md","publishedAt":"2021-12-01T00:59:21+09:00","updatedAt":"2021-12-01T01:30:59+09:00","commitCount":4,"cover":{"path":"post-images/v1/9cPn0k2Z.png","width":1200,"height":630}},
{"pathname":"/2021/nextjs12","title":"Next.js 12にしました","filePath":"src/pages/2021/nextjs12/index.page.md","publishedAt":"2021-10-29T22:24:14+09:00","updatedAt":"2021-11-25T12:56:34+09:00","commitCount":4,"cover":{"path":"post-images/v1/FqWvXwk8.png","width":1200,"height":630}},
{"pathname":"/2021/nextjs-https","title":"Next.jsの開発環境をHTTPSにしました","filePath":"src/pages/2021/nextjs-https/index.page.md","publishedAt":"2021-10-11T00:26:45+09:00","updatedAt":"2021-11-25T12:56:34+09:00","commitCount":4,"cover":{"path":"post-images/v1/ZX-cXk49.png","width":1200,"height":630}},
{"pathname":"/2021/nextjs","title":"サイトをNext.js + Vercelに移行しました","filePath":"src/pages/2021/nextjs/index.page.md","publishedAt":"2021-10-05T23:51:46+09:00","updatedAt":"2022-02-05T18:28:24+09:00","commitCount":10,"cover":{"path":"post-images/v1/s373Le5-.png","width":1200,"height":630}},
{"pathname":"/markdown","title":"Markdownテストページ","filePath":"src/pages/markdown.page.md","publishedAt":"2021-09-30T00:39:26+09:00","updatedAt":"2021-10-29T19:41:47+09:00","commitCount":17,"cover":{"path":"post-images/v1/tiihd--T.png","width":1200,"height":630}},
{"pathname":"/","title":"トップページ","filePath":"src/pages/index.tsx","publishedAt":"2021-09-29T00:33:31+09:00","updatedAt":"2021-10-28T22:22:49+09:00","commitCount":15,"cover":{"path":"post-images/v1/il7asoJj.png","width":1200,"height":630}}
]`);
export const pageListByUpdatedAt: Array<PageData> = (JSON.parse("[6,0,1,2,3,4,5,7,8]") as Array<number>).map((index) => pageListByPublishedAt[index]);
